### ISSUE TITLE
use "|" as separator in the verbose

### ISSUE THREAD

**Issue by lunebellec** [SIMEXP/psom#101]
This will give log lines like this:

`Pipeline terminated | 10-Sep-2016 15:25:59 | 0 run | 0 fail | 123101 done | 0 left`

instead of:

`Pipeline terminated on 10-Sep-2016 15:25:59 (0 run / 0 fail / 123101 done / 0 left).`

**Comment by lunebellec** [comment]
@poquirion @cdansereau @surchs thoughts?

**Comment by surchs** [comment]
+1 makes sense | looks better

**Comment by poquirion** [comment]
done
