### ISSUE TITLE
psom_run_script illegal characters

### ISSUE THREAD

**Issue by angela-tam** [SIMEXP/psom#132]
Lines 411 and 412 of `psom_run_script` contain # signs which don't work in MATLAB and gives the following error when trying to run a pipeline :

Error: File: psom_run_script.m Line: 411 Column: 9
The input character is not valid in MATLAB statements or expressions.

Error in psom_run_pipeline (line 505)
[flag_failed,msg] = psom_run_script(cmd_deamon,script_deamon,opt_script,opt_logs);

(ps. looks like those lines are supposed to be comments?)

**Comment by lunebellec** [comment]
that's correct

 "#" should be replaced by "%"

We NEED a proper testing procedure, that runs on both Matlab and Octave. 

@angela-tam can you fix this?
