### ISSUE TITLE
pipeline crashes because of empty heartbeat

### ISSUE THREAD

**Issue by surchs** [SIMEXP/psom#21]
While preprocessing the myconnectome data on guilimin with 100 jobs, my pipeline crashed with this message:

```
Something went bad ... the pipeline has FAILED !
The last error message occured was :
load: file `/gs/project/gsf-624-aa/database2/myconnectome/out/fmri_preprocess/logs/slice_timing_sub1_session1_run62.heartbeat.mat' seems to be empty!
File /sb/home/surchs/code/psom/psom_job_status.m at line 172
File /sb/home/surchs/code/psom/psom_pipeline_process.m at line 452
File /sb/home/surchs/code/psom/psom_run_pipeline.m at line 427
File /sb/home/surchs/code/niak/pipeline/niak_pipeline_fmri_preprocess.m at line 848
File /gs/project/gsf-624-aa/database2/myconnectome/scripts/mcn_preproc.m at line 104
```

I checked qstat and all the other jobs were still running happily. Not sure what may have happened. Is there a chance that the heartbeat gets confused if there are too many jobs?

I'll rerun the pipeline and see what that does.

**Comment by lunebellec** [comment]
So I think this is a race condition. The pipeline manager probably happened to try to read the file just while it got created. Didn't think about that ... I may have to skip the first read by the manager.
