### ISSUE TITLE
More meaningful overview of failed jobs

### ISSUE THREAD

**Issue by surchs** [SIMEXP/psom#24]
When a job with many children fails in a very large pipeline, the list of failed jobs is very long - but from a user's point of view, all the jobs after the failed parent job are probably less interesting. It would be great if the list of failed jobs would have a separate section near the end that shows explicitly the parent job that failed (and then caused all the children to fail as well).

**Comment by lunebellec** [comment]
Thanks for catching this one! Yes, that is definitely in line with my current effort to limit the amount of useless verbose PSOM generates.

**Comment by lunebellec** [comment]
OK so I removed the list of failed jobs and their children altogether. Now, only the number of failed/unprocessed jobs will be displayed. There is an example of call to psom_pipeline_visu, with one job that actually failed. The complete list of failed jobs can be accessed with psom_pipeline_visu.

**Comment by lunebellec** [comment]
This commit should fix the issue:
https://github.com/SIMEXP/psom/commit/cbc628bdff6261ccb3e629b38407116113861876
